### PR TITLE
Data tab to table tab #1883

### LINKED ISSUE #1883: Move data tab to table tab
Now that we have our great `table` option next to the chart, the `data` tab seems redundant. The main use for the data tab is progressive enhancement (no JS or IE8)

Can we combine the data tab with the table tab, is it difficult? I think the main issue is how it works without JS. Things to consider:

* Must initially have the headline data table, and download button
* Chart tab shouldn't be there unless JS is
* Tab (key) movement through the page must still flow well
* Move the download source data button here

What I also like about this is that the metadata will be visible as soon as the page loads. Always felt a bit hidden.

Estimate: 3 hours (Doug)

### PR DESCRIPTION
**Pull request by dougmet**
* Remove the headline data table in the bottom tabs.
* Move the static progressive enhancement version there as well.
* Rapidly hide the static version when JS is on (reduce flickering)

Fixes #1883

### CODE REVIEW

**Comment by shaneporter** [comment]
Hi @dougmet - I've removed the IE conditional comments (which effectively reinstated that headline table) and used modernizr's classes (which indicate support for the blobconstructor, which IE reports as false for those lower versions), and JS.

Please can you have a new look and see if things are behaving as you expect? Thanks.

**Comment by shaneporter** [comment]
IE9 shows the 'dynamic' table (defaulting to headline where applicable, but otherwise some 'default' selection) but does _not_ permit the downloading of this dynamic data.

There is a blob polyfill, as well as a typedarray polyfill, but with both of these, IE9 users don't see an error, but they are still unable to download the content.

**Comment by dougmet** [comment]
I'll sort conflicts after Ben's next PR goes in, I think we're all dabbling in the same area at the mo!

**Comment by dougmet** [comment]
If blob isn't available you now get a `Download Headline CSV` button. Buttons added to chart as well.

**Pull request merged**
