### PR TITLE
Update high-contrast CSS Rules

### LINKED ISSUE #1932: High contrast units contrast is insufficient
Take a look at the units section (2.3.1 for example) with JS enabled.

### PR DESCRIPTION
**Pull request by gingerbenw**
Resolves #1932 and #1928

Updated css rules for tables and unit measurements as well as generic page buttons and tabs.

### CODE REVIEW

**Comment by gingerbenw** [comment]
It was not meant to fix said issue! I will raise a ticket for this separately.

**Comment by dougmet** [comment]
Then I remove my concerns!

**Comment by dougmet** [comment]
I'll let you sort the conflicts 😬

**Comment by dougmet** [comment]
The only difference is that the `tabindex` attribute has been set in the `<div>` in one branch and the `<h3>` in the other.

**Comment by dougmet** [comment]
Took a deep breathe and reckoned you must have moved the tabindex to the `<h3>`s so that they'd expand properly.

**Pull request merged**
