### PR TITLE
8.b.1 deleted data

### PR DESCRIPTION
**Pull request by AlexLewis1**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by AlexLewis1** [comment]
#143 This an issue with the data

**Comment by dougmet** [comment]
Can I confirm you just want to remove all the data from the site?

**Comment by dougmet** [comment]
Ah I see. The whole indicator page needs to be removed.

**Comment by dougmet** [comment]
I've reset it to the default dataset. We really need to implement an active flag in the metadata which will completely ignore indicators that are not yet being reported.

**Pull request merged**
