### PR TITLE
Added metadata 8.2.1

### PR DESCRIPTION
**Pull request by AlexLewis1**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by AlexLewis1** [comment]
Hi Doug, is there a way in the editor to upload formulas in a desirable format? As when I have put in the formula for the numerator and denominator they are presented on a single line and will be quite hard to read.

**Comment by dougmet** [comment]
As in the numerator and denominator are in separate boxes? We can probably do something about this on the front end, I'm not so sure about the editor. At least no easily.

**Comment by AlexLewis1** [comment]
Yea those two. It might be good if we can have it looking good on the front end that's the important part. We don't need it in the editor really.

**Comment by dougmet** [comment]
OK, I've logged it in #97. Will think about what we can do.

**Pull request merged**
