### PR TITLE
Updated metadata fields where appropriate

### PR DESCRIPTION
**Pull request by AlexLewis1**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by AlexLewis1** [comment]
Hi Doug, I can't see this metadata on the site, is there another step I need to take?

**Comment by dougmet** [comment]
Me neither. Can I just check what you expect to see? Looks like the only update was a source URL

**Comment by dougmet** [comment]
It looks like you may have edited fields in the bottom `raw-metadata` box rather than the official fields. I'll try moving them and you can let me know if it looks right.

**Comment by AlexLewis1** [comment]
I've done this with several other indicators. Would you like me to update them or would it be better if you moved them as well? I don't mind either way

**Comment by AlexLewis1** [comment]
Hi Doug, did you get a chance to view my comment yesterday?

**Comment by dougmet** [comment]
Hi Alex, sorry, I lost track of this thread! If you know where they all are then yes, although there may be a problem with prose just at this moment that I need to resolve. Can you list here the affected indicators?

**Comment by AlexLewis1** [comment]
It's fine, I think this is why it might be a good idea to use the issues section. I'll post the indicators with this issue on there and do that with any problems from now on.

**Pull request merged**
