### PR TITLE
Accessible table of selections (fixes #1150)

### LINKED ISSUE #1150: Accessibility: Accessible Alternative
Broken off #1067 

This covers the hard bit. When the chart updates a person with a screen reader has no way to see the changes.

>  An accessible alternative that displays all of the ratios is also required.

### PR DESCRIPTION
**Pull request by shaneporter**
I think this PR contains the basics for a fix for 1150, but as is the case with these things, there are a few improvements to be had (separate issues for those, I think):

1. The table could do with some headings at the bottom; smaller screen users scrolling down may lose the context of the column because the top heading is lost.
2. The year column should be fixed when scrolling across.

Also, although there is a restriction on the number of simultaneous lines shown on the graph, it doesn't apply with a table, so all selections should be shown I think.

Note that there are some references to 'fixed columns'; these are in place for the expected 'keep the year column where it is when scrolling' enhancement.

### CODE REVIEW

**Comment by gingerbenw** [comment]
Oh noes, I appear to have found a borked page :( 
8-9-2

**Comment by gingerbenw** [comment]
Looks to be working really nicely in other indicators! Great job 👍  Will we be removing the 'accessible alternative' button from the top of the page?

**Comment by shaneporter** [comment]
So, we found that the error on 8-9-2 was related to outdated edge data, and the error was occurring in another part of the code.

I've updated the PR by fixing some nested `.row` elements and removing the 'Accessible Alternative' button.

Please take a look @gingerbenw / @dougmet - thanks

**Comment by gingerbenw** [comment]
Yup, looks great - working perfectly 👍 

re-merged

**Pull request merged**
