### PR TITLE
Add FAQ to main menu #565

### PR DESCRIPTION
**Pull request by dougmet**

### CODE REVIEW

**Comment by dougmet** [comment]
Hi @gingerbenw This works nicely on desktop/mobile but might look bad on tablet:

image

Any suggestions? Wondering if we need to put it to the left of the search menu, or think about adding some sort of a hamburger.

**Comment by dougmet** [comment]
Forget that. The search box expands when you select it so can't put this to the left.

**Comment by gingerbenw** [comment]
I'd suggest we could either have a line break between the items at a certain size, or change the breakpoint for the mobile version of the menu so it comes in earlier.

**Comment by dougmet** [comment]
Merging now but will come back to fix.

**Pull request merged**
