### PR TITLE
3.2.2 Updated metadata

### PR DESCRIPTION
**Pull request by AlexLewis1**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by dougmet** [comment]
I notice there's quite a lot of info in the `source_other_info_1` field. Is that text also available at the source URL or is it that we're required to keep it next to our data?

**Comment by AlexLewis1** [comment]
This text can be found through the source URL through which displays another link to the methodology summary which displays a PDF link. 

I'm not sure if that explanation covers it but here's links you have to go through: 

1. Origional URL https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/childmortalitystatisticschildhoodinfantandperinatalchildhoodinfantandperinatalmortalityinenglandandwales

2. Methodology 
https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/qmis/childmortalitystatisticsqmi

We could just have the methodology link in this section. So a link in addition to the original URL.

**Comment by dougmet** [comment]
I was about to say I don't mind. But it doesn't look very good on the current page. See this image (the text continues quite a lot more of the screen).

I can help to link to relevant sections if that's acceptable.

image

**Comment by AlexLewis1** [comment]
Yea that is quite messy, we should probably link straight to the methodology page instead.

**Comment by nathaneastwood** [comment]
I'm closing this as it is now succeeded by 8636662

**Pull request closed without merging**
