### PR TITLE
Addresses issue #144

### PR DESCRIPTION
**Pull request by nathaneastwood**
This PR addresses issue number #144 and allows a user to download the repo and reset it for their own country. It adds 3 new files

- [`requirements.txt`](https://github.com/datasciencecampus/sdg-indicators/pull/189/files#diff-e23410e320fcc2089f841942edcbe073)
- [`change_configs.py`](https://github.com/datasciencecampus/sdg-indicators/pull/189/files#diff-d74ba9f9eb76938083c01de6e4e23cef)
- [`reset_csvs.py`](https://github.com/datasciencecampus/sdg-indicators/pull/189/files#diff-8f7f90daa7c1526cf4d7b2df1086f8ec)

## Requirements

The user should first ensure their system has `python3` installed. Open the command line and type

```
python --version
```

If it is not installed, go and install it [from here](https://www.python.org/downloads/), otherwise, at the command line change directory (`cd`) into the `scripts` folder of the repository and run

```
pip install -r requirements.txt
```

This will install the relevant Python modules needed. 

## Resetting the Data

Once the requirements are installed, the user can reset the csv files stored in `/data`. This can be done by typing

```
python3 ./reset_csvs.py
```

## Resetting the `_config*` Files

In order to reset the 3 config files ([`_config.yml`](https://github.com/datasciencecampus/sdg-indicators/blob/gh-pages/_config.yml), [`_config_prod.yml`](https://github.com/datasciencecampus/sdg-indicators/blob/gh-pages/_config_prod.yml) and [`_config_staging.yml`](https://github.com/datasciencecampus/sdg-indicators/blob/gh-pages/_config_staging.yml)), the user can use the `reset_yaml` function. The useage is as follows:

```
reset_yaml [-h] -f FILE [-r REPO] [-n NAME] [-a ADJECTIVE] [-o ORG]
```

Again at the command line, type

```
python3 ./change_configs.py ...
```

where `...` represents some of the following options:

```
-h, --help                           show this help message and exit
-f FILE, --file FILE                 str: The file name.
-r REPO, --repo REPO                 str: The new repository name
-n NAME, --name NAME                 str: The new country name
-a ADJECTIVE, --adjective ADJECTIVE  str: The new country adjective
-o ORG, --org ORG                    str: The new organisation name
```

### CODE REVIEW

**Comment by nathaneastwood** [comment]
I see no reason why not. I put it in `/reset_scripts` to keep it separate, but I'll move it :)

**Comment by dougmet** [comment]
I don't see the files at all any more. Did the new directory get added properly?

Anyway. Something like `scripts/reset` might work well. We probably need to clean some of those scripts out anyway so it shouldn't be too cluttered in there.

**Comment by dougmet** [comment]
Also, are you happy for me to squash this when I merge?

**Comment by nathaneastwood** [comment]
Sorry, my bad. I didn't `git add` the moved files, only the deleted ones. By all means, squash away, I was meaning to do it myself.

**Pull request merged**
