### PR TITLE
9.2.1 Data

### PR DESCRIPTION
**Pull request by AlexLewis1**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by AlexLewis1** [comment]
@nathaneastwood This error is a bit strange, as I have called the column at the end value, or is there something I'm missing?

**Comment by nathaneastwood** [comment]
It doesn't look as though the data is formatted correctly. See here: https://github.com/AlexLewis1/sdg-indicators/blob/fa8b55ee2ae5359d44f2f73ff3a7784e44c9faf5/data/indicator_9-2-1.csv

**Comment by AlexLewis1** [comment]
I see that this error comes up when i've clicked through the details button on the travis build error. 

"Last column not called "Value" in data/indicator_9-2-1.csv
The command "ruby ./scripts/csvcheck.rb" exited with 1."

I'm sorry, I couldn't see what you were referring to on your link.

**Comment by nathaneastwood** [comment]
So essentially the link is a link to the csv file (look under files changed and click View). Value isn't the last column.

**Pull request closed without merging**
