### PR TITLE
add 3 more sources 

### LINKED ISSUE #2564: Add sources 4 & 5 display functionality [MUST FIX]
Occasionally indicators will require more than 3 sources, we need functionality for 2 additional source 'slots'

### PR DESCRIPTION
**Pull request by dougmet**
Fixes #2564

Sources all at the bottom now so you don't have to scroll down so far to find other fields.

### CODE REVIEW

**Comment by dougmet** [comment]
@MaxEngledewAdmin go ahead and test this now! Hard to test locally so I'll make a new branch with fixes if this isn't right.

**Comment by MaxEngledewAdmin** [comment]
testing it out now - https://datasciencecampus.github.io/sdg-indicators/9-5-1/ already had 5 in it but doesn't seem to playing displaying properly at the moment - will try editing the .md

**Comment by Norric1Admin** [comment]
Tried several metadata uploads but they have all errored so far. Tried removing @, " and &, I'll check if there's anything else.

**Comment by dougmet** [comment]
I see 5 in 9-5-1. But the last two look the same. 

I think @Norric1Admin your issues are because of smart quotes. See #2589 for more discussion.

**Pull request merged**
