### PR TITLE
3.2.2 Changed the column header from country coverage to geographical coverage

### PR DESCRIPTION
**Pull request by AlexLewis1**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by dougmet** [comment]
Liking the new `{{indicator_number}} {{Message}}` format. Do you want me to approve or a data manager?

**Comment by AlexLewis1** [comment]
Would you be able to approve this please. Is the "files changed" tab the best way for the data manager to view changes?

**Comment by dougmet** [comment]
Yes files changed is a nice way to view it. We can also look at getting you guys set up with the GitHub Desktop app (available from the ONS store thing I think) so that you can check out changes locally and look at them in Excel or whichever tool you're most comfortable with

**Comment by AlexLewis1** [comment]
That could be really useful. I'll have a chat the guys that will be using this and see if they think this will help them. We should probably have it anyway

**Comment by AlexLewis1** [comment]
On the site I can't see most of the fields of disaggregation when i select them, I can see age and geographical coverage but not the rest. Is this a problem my end or your end?

**Comment by dougmet** [comment]
I think this relates to the fact that we only have these data for England and Wales. See #98. If you click region then suddenly data appears. The data we want should appear in the `Breakdown by Region AND Birth Weight` table at the bottom. We haven't got this on the plot yet.

**Pull request merged**
