### PR TITLE
3.2.1 Data (v1)  - headline backdating

### PR DESCRIPTION
**Pull request by MaxEngledew**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by dougmet** [comment]
I can see there's a lot of white space around "England". Sometimes "England          ". I can ask @shaneporter to look at trimming whitespace from the end. Otherwise it's best avoided as it causes England to be picked up multiple times as a field.

**Comment by dougmet** [comment]
Even GitHub is trimming the whitespace from my comment!

**Comment by MaxEngledew** [comment]
@dougmet An auto-trimming feature would be very handy - it seems that this is a frequently occurring issue which is only highlighted if it happens to "Year " or "Value ". I think this would be a useful feature in terms of building the international capability of the tool - as Alex and myself frequently evidence - it would really reduce the number of Travis build failures! 

With the disaggregation names its probably due to inconsistent formatting across source data tables.. For the time-being we'll look out for this when we create the csvs and correct any current mistakes.

**Comment by dougmet** [comment]
See https://github.com/datasciencecampus/sdg-indicators/issues/303

**Pull request merged**
