### PR TITLE
Added data to 8.b.1

### PR DESCRIPTION
**Pull request by AlexLewis1**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by AlexLewis1** [comment]
This indicator does not have one headline disaggregation, it actually has 2. Will we be able to work around this in terms of plotting the disaggregation for each headline on the line graph?

**Comment by dougmet** [comment]
Is that `As a percentage of GDP` and `As a percentage of national budget`?

**Comment by dougmet** [comment]
My first thought is that we select that disaggregation by default somehow. Could be useful for the England and Wales problem, #98, too. What do you think @shaneporter ?

**Comment by shaneporter** [comment]
So, as an example, are you suggesting that we need to initially show 'All' and 'Geography', like this:

image

We could add a 'default disaggregation' to an indicator, which could be picked up by the JS. If my assumption here is correct, it shouldn't take too long to do at all.

**Pull request merged**
