### PR TITLE
Search works on IE

### PR DESCRIPTION
**Pull request by shaneporter**
Bad @shaneporter for assuming (after not having to think about IE for so long) that Promises were just understood by one and all. The indicator search uses them, so IE wasn't happy.

Using [bluebird](https://github.com/petkaantonov/bluebird) for Promises, so no other code changes in that area are needed, and all the browsers are happy.

I also ditched the loading SVG and replaced with a gif, so that IE was happy with that too.

### CODE REVIEW

**Comment by dougmet** [comment]
This works for me on IE11-Windows 10. Still getting the dialog box. Is that a different issue?

**Comment by shaneporter** [comment]
Ah, yes I pushed a single change to `develop` for an alert that I was seeing (because it was separate to the search weirdness). Please could you check the `develop` branch? If you still see it, please could you let me know the steps to reproduce?

Thanks @dougmet.

**Comment by dougmet** [comment]
oh ok great. I didn't merge with develop. Will merge this in now and take a look.

**Comment by dougmet** [comment]
OK dialog still there. It says "default" or "high" depending which contrast mode you're in. Will clobber @gingerbenw with another ticket!

**Pull request merged**
