### PR TITLE
Added data 5.2.1

### PR DESCRIPTION
**Pull request by MaxEngledew**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by dougmet** [comment]
Are you OK for me to bulk change `year1 - year2` e.g. `2005 - 2006` to `year1` (e.g. `2015`)? I might have to update the data checker to enforce this in future but I'm happy to do the change for this PR though.

**Comment by MaxEngledew** [comment]
Hi Doug, yes we're happy for you to do that for now but I think Ann would like to discuss this in the future. The data is 04-05 because its runs for financial years; so we will probably need a way to capture footnotes to add to the charts.

**Comment by dougmet** [comment]
OK that's done. I've added a ticket #136 to take care of the footnote

**Comment by dougmet** [comment]
Hmm. The disaggregation columns aren't showing up now that it's live. On the face of it the data looks well formatted. Any thoughts @shaneporter ? There's a javascript error that I can't quite work out. Could it be the column names?

**Comment by dougmet** [comment]
There are no completely empty columns. There are 23 columns so I don't know if there's some limit on the js side

**Comment by MaxEngledew** [comment]
Its seems as though we're incorrectly missing the 2014 figure (correctly missing the 2007), so I'll QA and update the data today. A side point; I think we'll need a discussion about the pros and cons of adding lines across missing data points - in this case between 06-08, is this something that is easy to add?

**Comment by shaneporter** [comment]
Are you expecting to see this as a bar chart? Bar chart code is running, which is out of date somewhat with the line chart code.

**Comment by MaxEngledew** [comment]
@shaneporter Ok thanks, we'll have a think about this then. This should be a line chart.

**Comment by shaneporter** [comment]
PR for line chart is #140

**Pull request merged**
