### PR TITLE
Hide all child field values that don't have data

### PR DESCRIPTION
**Pull request by brockfanning**
Here's a possible approach to #1204. I'm new to underscore and this project both, so there are probably more efficient ways to do this. Just throwing this out there in case it helps get the ball rolling. Also some notes:

* This includes CSS to hide the field items without data, but it could be changed to disable them instead.
* More work needed: there should also be some indication of when a child field has 0 available items, similar to the "Selectable when..." message. This could be either hiding the child field altogether (the whole dropdown) or some message like "No options available for this set of filters".

### CODE REVIEW

**Comment by dougmet** [comment]
Hi @brockfanning, thanks this is great! Have requested a review from @shaneporter as he'll have better context for the rest of the code.

To both of you, I did manage to break it in one place. `/sdg-indicators/8-5-1/` . Possibly something to do with the fact that it's got a three-level hierarchy? Age Range > Occupation Category > Occupation Sub Category

**Comment by brockfanning** [comment]
@dougmet 8-5-1 seems to be working OK for me locally. Am I looking for a js error, or is it something more subtle?

I did notice that 9-2-1 breaks - in that case the culprit is a discrepancy in the capitalization of variable names in the data file and edges file:
https://github.com/datasciencecampus/sdg-indicators/blob/develop/data/indicator_9-2-1.csv
https://github.com/datasciencecampus/sdg-indicators/blob/develop/data/edges/edges_9-2-1.csv

**Comment by dougmet** [comment]
OK, I'll check again on 8-5-1. As for the edges file. I probably shouldn't have checked those into the repo as they're produced at build time and may have fallen out of sync with the data. If you run:

```sh
python3 scripts/build/edge_detect.py
```

that should do it. Alternatively, `scripts/build/cibiuld.sh` runs everything. If it helps I'll push latest edge files in.

**Comment by dougmet** [comment]
p.s. Sorry we’re being a bit slow reviewing. Both myself and our main JS dev are out of office right now.

**Comment by dougmet** [comment]
hmm, my console errors are gone now. Only difference I built on Mac rather than Linux this time.

**Comment by gingerbenw** [comment]
Once an option has been selected, the child still has 'Select All' available, which still functions. so you can still select all the regions in England when only Wales has been selected in the region dropdown, for example.

**Comment by gingerbenw** [comment]
I think if we can **disable** rather than hide, and include the 'Select All' button in that, I think it's all good.

**Comment by brockfanning** [comment]
Another change to deal with the UX issue I mentioned above. This starts off all field groups sorted alphabetically, and then makes sure that the selectable ones show up at the top.

By the way, feel free to suggest massive refactoring, or take this in another direction, etc. I won't be offended. :) Mainly just trying to get a feel for the project's architecture while doing something potentially useful.

**Comment by gingerbenw** [comment]
Hey @brockfanning, this is looking really good now! thank you 👍

**Comment by gingerbenw** [comment]
Only thing left now is to ensure that the 'Select All' button only checks the boxes where the label 'has-data=true'

**Comment by gingerbenw** [comment]
Please see line 163 of indicatorView.js

(that took **AGES** to figure out!)

**Comment by gingerbenw** [comment]
Looking good now - many thanks @brockfanning !

**Comment by brockfanning** [comment]
@gingerbenw Ah, thanks for catching that, cool. :)

**Pull request merged**
